-- Add social dashboard related tables
CREATE TABLE public.communities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text,
    image_url text,
    location text,
    latitude numeric NOT NULL,
    longitude numeric NOT NULL,
    member_count integer DEFAULT 0,
    activity_rate integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE public.community_members (
    community_id bigint REFERENCES public.communities(id) ON DELETE CASCADE,
    user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    role text CHECK (role IN ('admin', 'moderator', 'member')) DEFAULT 'member',
    joined_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    PRIMARY KEY (community_id, user_id)
);

-- Add RLS policies
ALTER TABLE public.communities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Communities are viewable by everyone" ON public.communities
    FOR SELECT USING (true);

CREATE POLICY "Community members are viewable by everyone" ON public.community_members
    FOR SELECT USING (true);

-- Create indexes
CREATE INDEX idx_communities_location ON public.communities(location);
CREATE INDEX idx_communities_member_count ON public.communities(member_count DESC);
CREATE INDEX idx_communities_activity_rate ON public.communities(activity_rate DESC);
CREATE INDEX idx_community_members_user_id ON public.community_members(user_id);

-- Seed initial data
INSERT INTO public.communities (name, description, image_url, location, latitude, longitude, member_count, activity_rate)
VALUES 
    ('Brooklyn Tech Hub', 'A community for tech enthusiasts in Brooklyn', 'https://images.unsplash.com/photo-1498050108023-c5249f4df085', 'Brooklyn, NY', -73.944158, 40.692532, 1234, 89),
    ('Creative Arts Collective', 'Artists and creators in Williamsburg', 'https://images.unsplash.com/photo-1513364776144-60967b0f800f', 'Williamsburg', -73.963244, 40.714001, 856, 76);